import { Geist, Geist_Mono } from "next/font/google";
import "./style/globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "ma7moud.dev",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/favicon_io/favicon.ico" },
    { rel: "apple-touch-icon", url: "/favicon_io/apple-touch-icon.png" },
    { rel: "shortcut icon", url: "/favicon_io/favicon.ico" },
    { rel: "icon", sizes: "96x96", url: "/favicon_io/favicon-96x96.png" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-b from-[#0b1220] via-[#110f22] to-[#1a1c2c] min-h-screen flex flex-col w-full bg-green-600`}
        className={`${geistSans.variable} ${geistMono.variable} antialiased absolute left-0 right-0 bg-gradient-to-b from-[#0b1220] via-[#110f22] to-[#1a1c2c] min-h-screen flex flex-col w-full bg-green-600`}
      >
        <NavBar />
          <main className="flex-grow">
            {children}
          </main>
        <Footer />
      </body>
    </html >
  );
}
