
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "../../Components/Footer";
import NavBar from "../../Components/NavBar";
import "./style/globals.css";



export const metadata = {
  title: "ma7moud.dev",
  description: "Generated by create next app",
  icons: [
    { rel: "icon", url: "/favicon_io/favicon.ico" },
    { rel: "apple-touch-icon", url: "/favicon_io/apple-touch-icon.png" },
    { rel: "shortcut icon", url: "/favicon_io/favicon.ico" },
    { rel: "icon", sizes: "96x96", url: "/favicon_io/favicon-96x96.png" },
  ],
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className="app flex flex-col min-h-screen">
        <NavBar />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
